=== ediaz23/crunchyroll-js-api/src/config/app-config-json-schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "help_url": {
            "type": "string",
            "title": "URL for Help WebView",
            "default": "https://help.crunchyroll.com/",
            "format": "uri"
        },
        "playhead_interval_ms": {
            "type": "integer",
            "title": "Value used for periodical saving of continue watching progress",
            "default": 30000,
            "minimum": 1
        },
        "app_legal_links": {
            "type": "object",
            "title": "App legal links",
            "properties": {
                "privacy_policy": {
                    "type": "string",
                    "title": "Privacy policy URL",
                    "default": "https://www.crunchyroll.com/privacy?mode=mobile",
                    "format": "uri"
                },
                "terms_of_service": {
                    "type": "string",
                    "title": "Terms of service URL",
                    "default": "https://www.crunchyroll.com/tos?mode=mobile",
                    "format": "uri"
                }
            }
        },
        "terms_of_service": {
            "type": "object",
            "title": "Terms of service",
            "properties": {
                "last_updated_date": {
                    "type": "string",
                    "title": "The date when terms of service updated",
                    "default": ""
                }
            }
        },
        "watch_page": {
            "type": "object",
            "title": "Watch Page",
            "properties": {
                "version": {
                    "type": "string",
                    "title": "Select watch page version",
                    "default": "v1",
                    "enum": [
                        "v1",
                        "v2"
                    ]
                },
                "experiment_name": {
                    "type": "string",
                    "title": "Experiment name",
                    "default": ""
                },
                "variation_name": {
                    "type": "string",
                    "title": "Variation name",
                    "default": ""
                }
            }
        },
        "objects_max_ids_per_request_allowed": {
            "type": "integer",
            "title": "Max ids count allowed per objects endpoint request",
            "default": 100,
            "minimum": 1
        },
        "content_api_service": {
            "type": "object",
            "title": "Content Service",
            "properties": {
                "playheads_upload_batch_size": {
                    "type": "integer",
                    "title": "Maximum amount of playheads to upload at once.",
                    "default": 500
                },
                "playheads_get_batch_size": {
                    "type": "integer",
                    "title": "Maximum amount of playheads to download at once.",
                    "default": 350
                }
            }
        },
        "user_benefits": {
            "type": "object",
            "title": "User benefits fetch",
            "properties": {
                "fetch_interval_sec": {
                    "type": "integer",
                    "title": "User benefits fetch interval in seconds",
                    "default": 3600,
                    "minimum": 1
                }
            }
        },
        "new_relic": {
            "type": "object",
            "title": "New Relic integration",
            "properties": {
                "is_enabled": {
                    "type": "boolean",
                    "title": "Enable New Relic integration",
                    "default": true
                }
            }
        },
        "in_app_updates": {
            "type": "object",
            "title": "In-app updates",
            "properties": {
                "is_enabled": {
                    "type": "boolean",
                    "title": "Enable In-app updates",
                    "default": false
                },
                "client_version_staleness_days": {
                    "type": "integer",
                    "title": "Number of days to pass since the update became available on the Play Store",
                    "default": 5,
                    "minimum": 0
                },
                "update_reminder_interval_sec": {
                    "type": "integer",
                    "title": "Interval between update reminders in seconds",
                    "default": 2592000,
                    "minimum": 0
                },
                "background_install_delay_sec": {
                    "type": "integer",
                    "title": "Time to pass before starting install in background in seconds",
                    "default": 180,
                    "minimum": 0
                }
            }
        },
        "singular": {
            "type": "object",
            "title": "Singular integration",
            "properties": {
                "is_enabled": {
                    "type": "boolean",
                    "title": "Enable Singular integration",
                    "default": true
                }
            }
        },
        "mega_fan_upgrade": {
            "type": "object",
            "title": "Mega Fan upgrade",
            "properties": {
                "version": {
                    "type": "string",
                    "title": "Select Mega Fan upgrade screen version",
                    "default": "v1",
                    "enum": [
                        "v1",
                        "v2"
                    ]
                },
                "experiment_id": {
                    "type": "string",
                    "title": "Experiment id",
                    "default": ""
                },
                "experiment_name": {
                    "type": "string",
                    "title": "Experiment name",
                    "default": ""
                },
                "variation_id": {
                    "type": "string",
                    "title": "Variation id",
                    "default": ""
                },
                "variation_name": {
                    "type": "string",
                    "title": "Variation name",
                    "default": ""
                }
            }
        },
        "user_interactions_tracking": {
            "type": "object",
            "title": "User interactions tracking",
            "properties": {
                "is_enabled": {
                    "type": "boolean",
                    "title": "Enable user interactions tracking",
                    "default": true
                }
            }
        },
        "in_app_review": {
            "type": "object",
            "title": "In-app review",
            "properties": {
                "is_enabled": {
                    "type": "boolean",
                    "title": "Enable in-app review",
                    "default": false
                },
                "interval_between_attempts_min": {
                    "type": "integer",
                    "title": "Interval between attempts in minutes",
                    "description": "The time in minutes that should pass between in-app review attempts.",
                    "default": 129600
                },
                "app_launches_count_trigger": {
                    "type": "integer",
                    "title": "App launches count trigger",
                    "description": "The amount of app launches that will trigger in-app review flow.",
                    "default": 5
                },
                "app_launches_period_trigger_min": {
                    "type": "integer",
                    "title": "App launches period trigger in minutes",
                    "description": "The time in minutes after which the app launches count will be reset.",
                    "default": 10080
                }
            }
        },
        "watch_page_rating": {
            "type": "object",
            "title": "Watch Page rating",
            "properties": {
                "is_enabled": {
                    "type": "boolean",
                    "title": "Enable Episode Rating feature on Watch Page",
                    "default": false
                }
            }
        },
        "content_maturity_rating": {
            "type": "object",
            "title": "Content Maturity Rating label",
            "properties": {
                "is_enabled": {
                    "type": "boolean",
                    "title": "Enable Content Maturity Rating label",
                    "default": false
                }
            }
        },
        "app_resume_screens_reload_intervals": {
            "type": "object",
            "title": "Screen reload intervals on resume in minutes",
            "properties": {
                "short_interval_minutes": {
                    "type": "integer",
                    "title": "Short reload interval",
                    "default": 3
                },
                "medium_interval_minutes": {
                    "type": "integer",
                    "title": "Medium reload interval",
                    "default": 20
                },
                "long_interval_minutes": {
                    "type": "integer",
                    "title": "Long reload interval",
                    "default": 480
                }
            }
        },
        "billing_notifications": {
            "type": "object",
            "title": "In Grace, Retry and Renew Subscription notification",
            "properties": {
                "is_in_grace_home_cta_enabled": {
                    "type": "boolean",
                    "title": "Enable In Grace cta on the Home feed",
                    "default": false
                },
                "is_in_grace_notification_enabled": {
                    "type": "boolean",
                    "title": "Enable In Grace notification",
                    "default": false
                },
                "is_on_hold_notification_enabled": {
                    "type": "boolean",
                    "title": "Enable On Hold notification",
                    "default": false
                },
                "is_renew_notification_enabled": {
                    "type": "boolean",
                    "title": "Enable Renew subscription notification",
                    "default": false
                },
                "experiment_id": {
                    "type": "string",
                    "title": "Experiment id",
                    "default": ""
                },
                "experiment_name": {
                    "type": "string",
                    "title": "Experiment name",
                    "default": ""
                },
                "variation_id": {
                    "type": "string",
                    "title": "Variation id",
                    "default": ""
                },
                "variation_name": {
                    "type": "string",
                    "title": "Variation name",
                    "default": ""
                }
            }
        },
        "email_verification_banner": {
            "type": "object",
            "title": "Email Verification Banner",
            "properties": {
                "occurrence_interval_after_dismiss_minutes": {
                    "type": "integer",
                    "title": "Occurrence interval after dismiss in minutes",
                    "default": 1440
                },
                "occurrence_interval_after_confirmation_minutes": {
                    "type": "integer",
                    "title": "Occurrence interval after confirmation in minutes",
                    "default": 15
                }
            }
        },
        "closed_captions": {
            "type": "object",
            "title": "Closed Captions",
            "properties": {
                "is_enabled": {
                    "type": "boolean",
                    "title": "Enable Closed Captions",
                    "default": false
                }
            }
        },
        "sony_music": {
            "type": "object",
            "title": "Sony Music",
            "properties": {
                "is_enabled": {
                    "type": "boolean",
                    "title": "Enable Sony Music",
                    "default": false
                }
            }
        }
    }
}

=== ediaz23/crunchyroll-js-api/src/config/app-config-default-production.json
{
    "help_url": "https://help.crunchyroll.com/",
    "playhead_interval_ms": 30000,
    "app_legal_links": {
        "privacy_policy": "https://www.crunchyroll.com/privacy?mode=mobile",
        "terms_of_service": "https://www.crunchyroll.com/tos?mode=mobile"
    },
    "terms_of_service": {
        "last_updated_date": ""
    },
    "watch_page": {
        "version": "v1",
        "experiment_name": "",
        "variation_name": ""
    },
    "objects_max_ids_per_request_allowed": 100,
    "content_api_service": {
        "playheads_upload_batch_size": 500,
        "playheads_get_batch_size": 350
    },
    "user_benefits": {
        "fetch_interval_sec": 3600
    },
    "new_relic": {
        "is_enabled": true
    },
    "in_app_updates": {
        "is_enabled": false,
        "client_version_staleness_days": 5,
        "update_reminder_interval_sec": 2592000,
        "background_install_delay_sec": 180
    },
    "singular": {
        "is_enabled": true
    },
    "mega_fan_upgrade": {
        "version": "v1",
        "experiment_name": "",
        "experiment_id": "",
        "variation_name": "",
        "variation_id": ""
    },
    "user_interactions_tracking": {
        "is_enabled": true
    },
    "in_app_review": {
        "is_enabled": false,
        "interval_between_attempts_min": 129600,
        "app_launches_count_trigger": 5,
        "app_launches_period_trigger_min": 10080
    },
    "watch_page_rating": {
        "is_enabled": false
    },
    "content_maturity_rating": {
        "is_enabled": false
    },
    "app_resume_screens_reload_intervals": {
        "short_interval_minutes": 3,
        "medium_interval_minutes": 20,
        "long_interval_minutes": 480
    },
    "billing_notifications": {
        "is_in_grace_home_cta_enabled": false,
        "is_in_grace_notification_enabled": false,
        "is_on_hold_notification_enabled": false,
        "is_renew_notification_enabled": false,
        "experiment_name": "",
        "experiment_id": "",
        "variation_name": "",
        "variation_id": ""
    },
    "email_verification_banner": {
        "occurrence_interval_after_dismiss_minutes": 1440,
        "occurrence_interval_after_confirmation_minutes": 15
    },
    "closed_captions": {
        "is_enabled": false,
        "remote_configurable": false
    },
    "sony_music": {
        "is_enabled": false,
        "remote_configurable": false
    }
}
